waypoint_control:
  ros__parameters:
    path_file_name: '/home/jason/Desktop/STUDY/Cobra-Driver/workspace/data/PATH.txt'
    look_ahead_distance: 4.0  # Example value
    default_throttle: 1.2 
    pid_parameters:
      p: 0.05  # Example value
      i: 0.0  # Example value
      d: 0.03 # Example value
