waypoint_control:
  ros__parameters:
    path_file_name: '/home/sbel/Desktop/Cobra-Driver/workspace/data/PATH_REAL.txt'
    look_ahead_distance: 3.0  # Example value
    default_throttle: 0.2
    pid_parameters:
      p: 0.24  # Example value
      i: 0.0  # Example value
      d: 0.0 # Example value
