waypoint_control:
  ros__parameters:
    path_file_name: '/home/jason/Desktop/STUDY/Cobra-Driver/workspace/data/PATH.txt'
    look_ahead_distance: 3.0  # Example value
    pid_parameters:
      p: 0.07  # Example value
      i: 0.1  # Example value
      d: 0.0 # Example value
